### ISSUE TITLE
PyRAF on conda does not support python3

### ISSUE THREAD

**Issue by 1900011604** [iraf-community/pyraf#102]
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyraf -> python=2.7

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.33=0
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.33
```
When I install pyRAF by `conda install -c pkgw/label/superseded pyraf` on [here](https://anaconda.org/pkgw/pyraf), this above is what it says.

**Comment by olebole** [comment]
This should be reported to (Astro)Conda, not to PyRAF.

**Comment by Firestar-Reimu** [comment]
I am not using astroconda to install.

**Comment by olebole** [comment]
The problem is that the current stable version of PyRAF (2.1.15) does not work with Python 3.9 or later because the version of `stsci.distutils` it requires depends on 2to3, which is no longer available. You should try to install the [release candidate 2.2.0RC1](https://pypi.org/project/pyraf/2.2.0rc1/).

PyRAF is not packaged for Conda, so you can't install it from there.

**Comment by Firestar-Reimu** [comment]
> The minimal Python required for PyRAF is 3.6, but it is recommended to use the latest available version. An installation in an virtual environment like venv or conda is possible.

So "an installation like conda" means the astroconda version?

Another question is that how to install iraf via python? If iraf need python2.7 I cannot start pyraf.

**Comment by olebole** [comment]
> So "an installation like conda" means the astroconda version?

No, it means that you can install PyRAF (manually, not as a Conda package) within the Conda virtual environment. But the Astroconda version is for Python 2 only. I however have no experience with Conda (or Astroconda), so you should discuss it there for the specifics.

> Another question is that how to install iraf via python? If iraf need python2.7 I cannot start pyraf.

IRAF is completely independent of Python and cannot be installed "via Python". IRAF itself also does not need Python (or Pyraf) at all; it comes with its own shell (ecl).
