### ISSUE TITLE
setting parameters for immatch.wcsmap  

### ISSUE THREAD

**Issue by yas-nakajima** [iraf-community/pyraf#104]
Setting parameters like the following works for , for example, apphot. 
[IN]
iraf.apphot.datapars.itime = 10.
print(iraf.apphot.datapars.itime)
[OUT] 
10. 

It also works for immatch.geotran, however, it doesn't for immatch.wcsmap. 
[IN]
iraf.immatch.wcsmap.fitgeom = 'rxyscale'
print(iraf.immatch.wcsmap.fitgeom)
[OUT]
general

Do I miss something? 

Using 
pyraf 2.1.15 
iraf-community 2.16.1+2021.06.14

Thanks.

**Comment by olebole** [comment]
Can you reproduce it with the current "main" branch? I get:
```Python
>>> from pyraf import iraf
>>> iraf.imgeom()
>>> iraf.immatch()
>>> print(iraf.immatch.wcsmap.fitgeom)
general
>>> iraf.immatch.wcsmap.fitgeom = 'rxyscale'
>>> print(iraf.immatch.wcsmap.fitgeom)
rxyscale
```
Therefore, I would guess that this will be fixed in the next release.
To try this out, install the current development version with pip:
```shell
pip3 install git+https://github.com/iraf-community/pyraf.git
```

**Comment by yas-nakajima** [comment]
It works! 

Thanks!
