### ISSUE TITLE
pyraf cannot update new iraf directories.

### ISSUE THREAD

**Issue by Firestar-Reimu** [iraf-community/pyraf#108]
1. I installed iraf from source, directory is `~/Downloads/iraf-2.16.1-2021.06.14`
2. I installed pyraf from pip
3. `mkiraf` and then `pyraf`
4. I moved iraf to a new directory `~/.iraf-source`
5. I deleted the old PATH and `export PATH=/home/firestar/.iraf/bin/:$PATH`
6. `mkiraf` and then `pyraf`, it said no directories found: `~/Downloads/iraf-2.16.1-2021.06.14/unix/hlib/zzsetenv.def`

PS: `epar` fonts are still small

**Comment by olebole** [comment]
If you move IRAF, you need to re-execute the `./install` script there, and make sure the the `iraf` environment variable (and `host` if it exists) point to the right installation.
Closing this, since it is not Pyraf related (it is a pure IRAF problem).
