### ISSUE TITLE
"Error in parameter" (sometimes) with additional pset dot syntax

### ISSUE THREAD

**Issue by jehturner** [iraf-community/pyraf#113]
I'm seeing quite a lot of Gemini IRAF tests failing with a message such as `KeyError: "Error in parameter 'centerpars.cthreshold' for task phot\n'Key centerpars.cthreshold not found'"`, using a recent checkout of iraf-community PyRAF for Python 3. All but one are cases where the failing IRAF task gets passed parameters from an "additional" pset (can't recall whether that's the proper IRAF terminology) in the form `centerpars.cthreshold=0.`.

For example, I see the error quoted above when doing the following with pyraf 2.2.1.dev3 and stsci.tools 4.0.1 on Python 3.7.9:
```
digiphot
apphot

phot dev$pix coords="" output="default" interactive- centerpars.calgorithm="none" centerpars.cthreshold=0.
```
This only happens some of the time, depending on the exact parameters used, due to the nature of the bug. With earlier PyRAF releases, the task instead continues to a prompt like the following in this particular case (which seems like dubious behaviour in itself, but that's a different problem!):
```
Centering algorithm (none) (CR or value): 
```
After a bit of troubleshooting, this seems to be a regression introduced by no longer running `2to3` on the source code (making it hard to spot, since there's no change to the offending line in the revision history!). Because `kw.keys()` no longer gets converted to a `list` by `2to3`, the following block of code is now modifying a `dict` in place while iterating over it (rather than over an existing copy of the keys), leading to unpredictable behaviour:

https://github.com/iraf-community/pyraf/blob/1a63a6525b2b95bdc0597b2b8e84c99f52eb829c/pyraf/irafpar.py#L912-L918

I think the solution is just to put L912 back to this (or use `copy` or something):
```python
        for key in list(kw.keys()):
```
Thanks!

James.

**Comment by jehturner** [comment]
I can add a PR for this. I'm not sure what would be the best way of including a test though; I was having trouble reproducing this behaviour using the Python interface.

**Comment by olebole** [comment]
Thank you so much for debugging this and for the fix!

**Comment by jehturner** [comment]
No problem. Sorry for the long delay. I'm looking at a couple of other problems (`CL syntax error at '='` and "`Write() argument must be str, not bytes`), then I think it's worth re-testing everything with the fixes that we already have (plus any other recent changes). A number of the test failures seem to be things like small numerical differences or extra WCS keywords and might have some mundane cause that's not really important and just needs (possibly laborious) test updates.

**Comment by jehturner** [comment]
There are also a couple of other error messages that look like Python 2 vs 3 string differences.

**Comment by olebole** [comment]
I am happy to get more bug reports and PRs!
