### ISSUE TITLE
Cursor issue interacting with graphics on Mac

### ISSUE THREAD

**Issue by carys-evans** [iraf-community/pyraf#130]
I am having an issue using my cursor on the graphics window on a Mac. It seems to work variably, so sometimes it's fine, but sometimes it gets stuck at won't move once it's on the graphics window. I am using iraf in conjunction with the python3 version of this pipeline:
https://github.com/svalenti/pessto
and was directed here after posting the issue to the pipeline repository.

A video demonstrating the issue I am having can be found here:
https://cf-my.sharepoint.com/:f:/g/personal/evanscr8_cardiff_ac_uk/Etzklvf_5VZAvQbcDMKOgZEBY2UVQgzhUqhvObBS3PRulg?e=XywCdF

System details:
 - OS: macOS Monterey Version 12.2
 - IRAF Version 2.17
 - PESSTO Pipeline Python3 branch

**Comment by olebole** [comment]
It is actually a PyRAF issue, so I moved it here.

Can you check this with a simple window ("implot dev$pix")?
With my test setup (MacOS 11 in a VirtualBox) I can't reproduce this then. It also may be a bug in the Python-Tk implementation on your Mac; it may be worth to play with these.

Best

Ole

**Comment by olebole** [comment]
This could actually also be the same issue as #107, so you may try out the workaround given there.

**Comment by carys-evans** [comment]
Using the fix in #107 I was able to get the cursor working!
