### ISSUE TITLE
pyraf - cannot get GUI windows for parameters

### ISSUE THREAD

**Issue by prdurrell** [iraf-community/pyraf#144]
Hi -- recently installed Iraf 2.17 and Pyraf 2.2.1 on MacOS Catalina 10.15.7.   The run_tests worked just fine for the IRAF install.   When running from xterm the usual IRAF windows (eg. imexamine) appear to work just fine, but when I try to **edit** parameters, Pyraf hangs and does not show the expected GUI window.    I am not sure if this is a pyraf issue or something else that I have set incorrectly.    
     I do get a python icon in the dock when I do this, but I am not sure what this means, or if something is not running properly.    
<img width="316" alt="Screen Shot 2022-08-12 at 1 39 42 PM" src="https://user-images.githubusercontent.com/48992231/184413914-f65dedbd-e20a-4e72-9235-a5931a265adb.png">

 running python 3.9.12, tk 8.6.11   

Pat Durrell

**Comment by olebole** [comment]
If you look into the "Window" menu on top, to you see a "PyRAF Parameter Editor" window listed? Another question is whether your Tk is built for X11 or for native macOS.

I would suspect that this is rather a Tk problem than a PyRAF problem, so you may need to dig in there. For example, if you run in a Python prompt
```python
>>> import tkinter
>>> tkinter.Tk()
```
do you see a simple, empty window popping up?

**Comment by prdurrell** [comment]
Hi - in 'Window' I only see 'xterm', and no 'PyRAF Parameter Editor'
 When I run the tkinter example in python I do see a small, empty window 

Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> tkinter.Tk()
<tkinter.Tk object .>
>>> 

<img width="232" alt="Screen Shot 2022-08-16 at 12 01 13 PM" src="https://user-images.githubusercontent.com/48992231/184925770-008b5554-01ba-41e9-b363-c985989f6122.png">
.

**Comment by olebole** [comment]
Before checking the "Window", you should switch to the Python icon. Otherwise, you probably see what is in X11, not what is in Python.

**Comment by prdurrell** [comment]
Still nothing showing up under 'Window' after I click the python icon.   That Python icon opens up when I run pyraf from the xterm.   However, I am still using bash and not zsh -- could that make a difference on what is being displayed?
<img width="534" alt="Screen Shot 2022-08-16 at 12 24 22 PM" src="https://user-images.githubusercontent.com/48992231/184930441-8f355eae-3952-4d4c-baf5-564ad1bdf893.png">

**Comment by olebole** [comment]
The shell isn't important here. However, since I don't have a Mac, I can't help more. I would recommend to try PyRAF with a different Python version -- the one that comes with macOS worked find as far as I could check. For more, I would need a system to check.

**Comment by prdurrell** [comment]
I can test with a different python version...thank you so much!

**Comment by lmytime** [comment]
I get the exact same problem on my Mac, @prdurrell  have you solved this problem?

**Comment by lmytime** [comment]
@monodera 
Great! Your solution works for me! Thank you very much.
I install pyraf using pip.  As your suggestion, I modify editpar.py file in stsci.tools package. And it is working now.

**Comment by olebole** [comment]
@monodera Thanks for the hint; it seems (f.e. [on stackoverflow](https://stackoverflow.com/questions/29158811/whats-the-difference-between-update-and-update-idletasks)) that one should really use `update_idletasks()` over `update()`.
Can you create a Pull Request? Then, I could check this out on Linux and merge if it appears to work well.

**Comment by prdurrell** [comment]
Hi;  I have not solved it yet...have been buried under a lot of other things so have not had time to get back to it.  I am looking forward to any ideas people have, or any way to narrow down the problem!
  Pat Durrell
________________________________

**Comment by lmytime** [comment]
@prdurrell You can try @monodera 's solution. Hopefully, it will also work for you.

**Comment by monodera** [comment]
@olebole I've just created a pull request. I hope this works. 

I noticed that there are several other places using `update()` for tkinter objects. I'm not sure whether they have the same issue or we can leave them as they are.

**Comment by lmytime** [comment]
There is another issue for epar in MacOS dark mode:
Some of texts in epar have not been set to `foreground = 'black', activeforeground = 'black'`. Therefore in dark mode, some texts are in white, which is indistinguishable. 
I have solved it by add some `foreground = 'black', activeforeground = 'black'` configure to some lines.

**Comment by lmytime** [comment]
Final performance:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/48662187/196784893-53f78eb1-4a86-4b2f-9dda-ea447eb8f819.png">

**Comment by prdurrell** [comment]
I did a quick test, and changing the three instances of update() to update_idletasks() seems to work for me.     Thanks so much for that solution @monodera !  That was some very nice detective work.

**Comment by olebole** [comment]
@lmytime If you also could create a Pull Request, this would be great.

**Comment by olebole** [comment]
Since #145 is merged, I am closing the issue.

**Comment by trappist1i** [comment]
I have the same issue than described in this post: typing epar for an iraf task does not open any GUI window and Pyraf just hangs. I searched my disk for an editpar.py file to try the solution of @monodera, but I didn't find any. Any help would be welcome!

I'm working with the following setup.
    MacBook Pro (16-inch, 2023) with M2 Pro + Python 3.11  + pyraf installed with pip3 + iraf v2.17
