### ISSUE TITLE
Pyraf rspectext RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by olebole** [iraf-community/pyraf#146]
Issue found by @TrentinErasmo on [stackoverflow](https://stackoverflow.com/questions/74066408):

> I have to convert a classic ascii file with two columns (wavelength and flux) into a fits file and I used rspectext from pyraf (with dtype=interp) in a python script but I get this error message:  
> 
>     Traceback (innermost last):
>     File "<CL script CL1>", line 1, in <module>
>     File "<CL script onedspec.rspectext>", line 54, in rspectext
>         iraf.hedit(Vars.specout, 'title', Vars.title, add=yes, 
>         addonly=no,PYdel=no,update=yes,verify=no,show=no)
>     RuntimeError: dictionary keys changed during iteration
> 
> I cannot understand what is wrong. I updated everything, followed guides to install both iraf and pyraf and on iraf, rspectext works. In other python scripts I use other commands like continuum, splot etc. and they work.
> 
> My script for a test is simply:
> 
>     from pyraf.iraf import onedspec,rspectext
>     onedspec
>     rspectext(input='test.dat',output='spectrum',dtype='interp')
>
> […]

**Comment by olebole** [comment]
That is PyRAF 2.2.0, from Ubuntu 22.04.

When running this from a Python prompt, one gets the full stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 836, in __call__
  return self.run(*args, **kw)
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 375, in run
  self._run(redirKW, specialKW)
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 1538, in _run
  self._runCode()
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 1554, in _runCode
  self._clFunction(*parList, **kw)
  File "<CL script onedspec.rspectext>", line 54, in rspectext
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 836, in __call__
  return self.run(*args, **kw)
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 358, in run
  self.setParList(*args, **kw)
  File "/usr/lib/python3/dist-packages/pyraf/iraftask.py", line 479, in setParList
  newParList.setParList(*args, **kw)
  File "/usr/lib/python3/dist-packages/pyraf/irafpar.py", line 912, in setParList
  for key in kw.keys():
RuntimeError: dictionary keys changed during iteration
```
which points to this piece of code: https://github.com/iraf-community/pyraf/blob/32455a4a4e1085b17b5a31ab767e4dd6b74dcbac/pyraf/irafpar.py#L912-L918

This code iterates over all keys and possibly possibly removes some and adds others. This worked for Python 2.X, but in Python 3 it raises the shown error.

Checking the last commits I found however that this is fixed in https://github.com/iraf-community/pyraf/pull/114/commits/2b4f24c0d2c60fcbe9e83d9c85902fa49f80bb20, which is part of [Version 2.2.1](https://github.com/iraf-community/pyraf/releases/tag/v2.2.1). So the best solution is to upgrade to the newest version, i.e. remove the Ubuntu package with *sudo apt remove python3-pyraf* and install the lastest from PyPI with *pip3 install pyraf*.

**Comment by veronicaloatac** [comment]
When I want to install pyraf using "pip3 install pyraf" I have a problem with "setuptools"

**Comment by olebole** [comment]
@veronicaloatac  you posted on an old, long resolved bug report for PyRAF. This is not the right place to start discussing a new problem.

Please open a new discussion on the [discussion forum](https://github.com/orgs/iraf-community/discussions) describing the problem you have. Include
* the operation system, distribution, and version you used. If using under Windows, specify which version and which Linux guest,
* the Python version,
* the IRAF version,
* the exact error message from setuptools,

One more comment: IRAF/PyRAF is really old software, nowadays lacks further development and and institutional support. It is mainly maintained for those who cannot switch yet. Unless there is a real strong requirement, it is a really bad idea to start with it for a new project. It would be much better to use modern Python projects like [Astropy](https://astropy.org/) instead whenever it is suitable. This is much more future-proof than learning an outdated, 40 year old legacy software system.
