### ISSUE TITLE
PyRAF splot cursor interaction with data display sluggish and/or clunky - problem with aqutil the cause?

### ISSUE THREAD

**Issue by WDplanets** [iraf-community/pyraf#156]
I'm grateful for all the work being done to keep the functioning of IRAF going.  

In Jan 2024 I did an install to my MacOS 10.15.7 (Catalina) system from here: https://iraf.noirlab.edu/

It seems to work, but in PyRAF, when I run the task 'splot' the cursor interaction with the display is sluggish and clunky.  I wonder if the clunky spectrum navigation may have something to do with the fact that when I start pyraf I get the following messages:
"Could not import aqutil"
"Limited graphics available on OS X (aqutil not loaded)"

Responding to my above comments, a leader at NOIRLab said the following, (and told me to post the issue in GitHub here):
"The 'aqutil' warning is coming from Pyraf where this is an internal set of routines for dealing with window interactions (e.g. focus, resizing, etc).  For most interactions it is harmless but it is likely the reason that the 'epar' window doesn't work and may be related to Tcl/Tk versions used in recent MacOS systems.  There are also known issues with cursor interactions that may be related to the same Tk problems."

For now, as recommended by NOIRLab, I will use the bare IRAF CL in an XGterm to work with astronomy spectra.  But I do hope going forward to be able to use PyRAF to run my PyRAF codes that interact with IRAF functions that have data displays.

Thank you for your attention.

**Comment by monodera** [comment]
For the `aqutil` warning, you can try to install `pyobjc` with `pip` or `conda`. Also, you can try to set an environment variable `PYRAFGRAPHICS` as `matplotlib`.

About the `epar` window issue, you can try the latest `main` branch of this repository which includes a fix for the issue. 

Maybe one solution (if you want to use the NOIRLab's IRAF 2.18) is to use the latest `main` for PyRAF after uninstalling NOIRLab's PyRAF.

**Comment by olebole** [comment]
@monodera Do you think it would be useful to add `pyobjc` as a platform specific dependency to `setup.cfg`? Like
```
install_requires = …
  pyobjc; sys_platform == "darwin"
```
(BTW; what about `AppKit` mentioned here? https://github.com/iraf-community/pyraf/blob/e41ad9fb17530e58c13d792c82327ad9802912a2/pyraf/aqutil.py#L12

And/or would be a new release useful?

**Comment by monodera** [comment]
I think it is useful as most users would worry about the warning, but I'm not sure if any side effects can happen or not (maybe some more disk space?).

About the new release, if the fix for the epar issue is considered stable, it's time to make a new release as most users will install pyraf just by `pip install pyraf`. Other groups (e.g., NOIRLab) would also rely on the 'official' release rather than the development head for their packages.

**Comment by olebole** [comment]
Independent of possible fixes here, NOIRLab should IMO install pyobjc in their distribution. I opened an issue there: [nsf-noirlab/csdc/usngo/iraf/pages!2](https://gitlab.com/nsf-noirlab/csdc/usngo/iraf/pages/-/issues/2)

**Comment by mjfitzpatrick** [comment]
Installation of pyobjc actually breaks pyraf on a MacOS Sonoma (14.3) system, i.e. `pip install pyraf` works but then doing a `pip install pyobj` causes the startup to fail with:

```
Traceback (most recent call last):
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple//bin/pyraf", line 8, in <module>
    sys.exit(main())
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/__main__.py", line 112, in main
    splash_screen = splash.splash(f'PyRAF {__version__}')
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/splash.py", line 219, in splash
    return IrafMonitorSplash(label, background=background, **kw)
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/splash.py", line 174, in __init__
    PyrafSplash.__init__(self, text=[None, label], **kw)
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/splash.py", line 92, in __init__
    wutil.forceFocusToNewWindow()
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/wutil.py", line 187, in forceFocusToNewWindow
    aqutil.focusOnGui()
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/aqutil.py", line 38, in focusOnGui
    raise Exception("SetFrontProcess: " + str(err))
Exception: SetFrontProcess: -13066
```

The PyRAF.app in this case is a miniconda system, adding pyobjc leads to the above regardless of distribution.  See perhaps https://stackoverflow.com/questions/28442944/getprocessforpid-not-deprecated

**Comment by olebole** [comment]
@mjfitzpatrick I opened a new issue for this #163.
