### ISSUE TITLE
Maplotlib window becomes blank when resizing

### ISSUE THREAD

**Issue by monodera** [iraf-community/pyraf#160]
The modification in #158 does not seem enough. A pyraf window with the matplotlib backend becomes blank when resizing. Pressing 'r' redraws the plot, but adding `self.draw_idle()` as in the reference web page #157 fixes it. 

I'll make a hotfix.

**Comment by monodera** [comment]
**Without fix**
https://github.com/iraf-community/pyraf/assets/90394/525bb177-cdc5-4097-bef0-90ecb8546987

**With fix**
https://github.com/iraf-community/pyraf/assets/90394/290864e4-5697-483f-8661-4975d12f562f

**Comment by olebole** [comment]
This seems to be fixed with #161; therefore closing. If this still happens, please reopen.
