### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by pllim** [iraf-community/pyraf#52]
As requested in https://github.com/spacetelescope/pyraf/pull/51#issuecomment-377612370 but after #53 is merged.

* GitHub
* Astroconda
* PyPI

**Comment by jehturner** [comment]
It would be good to have a new release with those fixes at some point, but we don't need it right now. I would actually prefer to wait and see whether we find any other problems, if you're not in a hurry (I'm going to run our package tests, but I need to convert them to support Python 3 first). Thanks for asking.

By the way, the conda package for `pyraf` lists `astropy` as a dependency, but grep does not find the string `astropy` anywhere in the package. Is that out of date, @jhunkeler?

**Comment by jhunkeler** [comment]
Would it make sense to move the `astropy` into `setup_requires`? The only modules using Astropy directly are in the test suite. The installation of `astropy` into the runtime environment should be handled by a package that actually needs it, like `stsci.tools` (as you pointed out).

**Comment by pllim** [comment]
Irrelevant now.
