### ISSUE TITLE
TST: How to check Jenkins results (SOLVED)

### ISSUE THREAD

**Issue by pllim** [iraf-community/pyraf#58]
1. Link to results for `master` is available at https://ssbjenkins.stsci.edu/job/STScI/job/pyraf/job/master/ (this link is also reachable by clicking the "build status" badge on README).

2. On left menu, click on "Open Blue Ocean".

3. Select row pointing to "master" branch.

4. Click on the Python 2 build as shown

![pyraf_jenkins_1](https://user-images.githubusercontent.com/2090236/38385028-c21a5ef0-38de-11e8-820e-a3a5330fa854.png)

5. To make sure, you will now see a line like `conda install -y -q python=2.7 iraf-all six` on that page below the diagram.

6. Expand the line with `with_env pytest tests --basetemp=tests_output --junitxml results.xml` to see Python 2 test results. Example:

```
[STScI_pyraf_master-52EC45PPOTV4YGTS2XRZCI6UCVSWOPR23BCYCLQME64HJ7JJ445Q] Running shell script

+ with_env pytest tests --basetemp=tests_output --junitxml results.xml

============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/jenkins/workspace/STScI_pyraf_master-xxx, inifile: setup.cfg
collected 76 items

tests/test_basic.py ....                                                 [  5%]
tests/test_clcache.py .                                                  [  6%]
tests/test_cli.py ....                                                   [ 11%]
tests/test_core_nongraphics.py .......x........x...xx..                  [ 43%]
tests/test_describe.py .                                                 [ 44%]
tests/test_graphics.py ..........s                                       [ 59%]
tests/test_invocation.py ........................                        [ 90%]
tests/test_using_tasks.py .......                                        [100%]

 generated xml file: /home/jenkins/workspace/STScI_pyraf_master-xxx/results.xml 
=============== 71 passed, 1 skipped, 4 xfailed in 21.12 seconds ===============
```

7. To see Python 3 build, click on the bottom-most circle in the diagram. Then, repeat steps similar to Python 2 build above to see its results. For Python 3, it is currently (as of this writing) allowed to fail, so it will show a green status but you will see some failures. Unlike Travis, Jenkins cannot set individual build to red without failing the whole thing, even if that individual build is an allowed failure.

c/c @cdsontag

**Comment by cdsontag** [comment]
Very cool @pllim !  and instructive.  Thank you for the help and diagram here.
