### ISSUE TITLE
MNT: Move pyraf out of spacetelescope into its own org?

### ISSUE THREAD

**Issue by pllim** [iraf-community/pyraf#60]
This came up in a conversation, so just documenting it in case there is real interest.

As STScI winds down its support in the future, it would be more useful for this package to be in its own organization so that people or other institution(s) out there who still rely on this package may ramp up their support of it.

There is already a precedence with https://github.com/airspeed-velocity/asv .

**Comment by olebole** [comment]
I think about creating a collection of repositories under a [iraf-community](https://github.com/iraf-community) organization, which then could be a base for future community development. This could include IRAF itself, x11iraf, important abandoned external packages (including STSDAS), and also Pyraf.

**Comment by pllim** [comment]
c/c @hcferguson

**Comment by olebole** [comment]
One other point that STScI could contribute is the script (`gethelp.pl`) that generated the STSDAS IRAF help pages; it seems to work around a number of bugs the standard lroff2html has.
STSDAS would be another one... (and maybe making it true open source).

**Comment by pllim** [comment]
> making it true open source

Due to some licensing issues that shall not be mentioned, true open source is currently not possible...

**Comment by olebole** [comment]
Just to remind here: before you are going to close and remove this repository, please consider donating(move) it to iraf-community. This would ensure that all the issues are kept, which would make future community maintenance much easier.

**Comment by perrygreenfield** [comment]
Nothing stops anyone from forking this repository. Speaking for myself (and not STScI), I would say go for it :-)

**Comment by olebole** [comment]
True, and I did this already (in my personal space, to not confuse people). However, a fork does not contain the original issues and pull requests, which may be worth to keep. Therefore I would prefer if STScI would "donate" (i.e. move) the repository instead of deleting it.

If there are other resources that are going to disappear (see #68 which triggered me to ping on this issue), it would be great if you could ping me as well -- especially when it comes to CL/Python/LaTeX source files. And it seems that STScI [prevents the archive.org](https://web.archive.org/web/*/http://www.stsci.edu/resources/software_hardware/pyraf) from saving your history.

**Comment by perrygreenfield** [comment]
I'll look into how that can be done.

**Comment by pllim** [comment]
Re: Transfer -- Some permission issues need sorting out between the two orgs, but we have done it before for other things, so it is definitely possible. Would be nice to see a closure to this issue after more than 2 years. Thanks!

Also see: https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by perrygreenfield** [comment]
It needs a couple approvals, one achieved so far, but waiting on the other after the weekend (person is out on vacation).

**Comment by pllim** [comment]
As discussed offline, all the necessary approvals have been received. Please proceed as planned. Thanks!

**Comment by perrygreenfield** [comment]
I created an issue on the iraf repository earlier.

**Comment by perrygreenfield** [comment]
I've also asked him if we can retrieve the trac history.

**Comment by pllim** [comment]
Move is done! 🎉
