### ISSUE TITLE
matplotlib graphics fails

### ISSUE THREAD

**Issue by jrthorstensen** [iraf-community/pyraf#72]
Hello everyone --

I've just installed the community iraf and pyraf on a Fedora-33 system to be sure that it will work correctly on newer linuces where 32-bit binaries are no longer supported.  

One minor detail -- on older systems I have been setting the environment variable PYRAFGRAPHICS to 'matplotlib', which leads to somewhat nicer graphics rendering.  This now fails with the message:

```
/usr/local/lib64/python3.9/site-packages/pyraf-2.1.15-py3.9-linux-x86_64.egg/pyraf/MplCanvasAdapter.py:21:
MatplotlibDeprecationWarning: 
  The 'resize_callback' parameter of __init__() was deprecated in Matplotlib 3.4 and will be removed two minor
  releases later. Use get_tk_widget().bind('<Configure>', ..., True) instead. If any parameter follows
  'resize_callback', they should be passed as keyword, not positionally.
  tkagg.FigureCanvasTkAgg.__init__(self, figure, master,
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
AttributeError: 'MplCanvasAdapter' object has no attribute 'show'
```

I'm running matplotlib version 3.4.2, with python 3.9.6.

Any ideas?  If this is an easy fix, it'd be nice to have.

Thanks -- John

**Comment by jrthorstensen** [comment]
Ole -- 
I managed to get it running (took a little bit because I had a previous pyraf I needed to get rid of) and that seems to have fixed the problem nicely!
Thanks - John

**Comment by olebole** [comment]
Thank you for testing. I I will merge #73...
