### ISSUE TITLE
New Pyraf version on PyPI

### ISSUE THREAD

**Issue by olebole** [iraf-community/pyraf#86]
Hello @cdsontag, @stsci-ssb-ci (or @plim?),

since I am getting done with the Python 3 transition, I would also like to create a new version and push it to PyPI soon. However, the [pyraf project](https://pypi.org/project/pyraf/) there is still maintained by you (cdsontag, stsci-ssb). Could I ask to add me to the maintainer's list there so that I can upload new versions without bugging you?

Thank you very much!

Ole

**Comment by cdsontag** [comment]
Makes sense.  I tried to invite "olebole" as a maintainer but I don't know how pypi knows who that is on github.

I think the right person at ST now is @pllim

**Comment by olebole** [comment]
Worked nicely. I am now maintainer, as my nickname on PyPI is the same as here :-)
Thank you very much for the quick action!

**Comment by olebole** [comment]
Just for the record: I am maintainer on PyPI, not owner. In case you leave completely, please make me owner before.

**Comment by pllim** [comment]
I am not sure why STScI should hold on to it. We don't develop it anymore. Hmm... I'll ask around and get back to you.
